module WaifuRuntime (waifuRuntimeASM, valTagNames) where

-- | Runtime assembly for WaifuLang lists, maps, strings, and tagged values.
-- Value layout: 16 bytes { tag: int64, data: int64/ptr }
-- List layout: { len, cap, items* }
-- Map layout:  { len, cap, entries* } where entry = { key*, val(16) }

valTagNames :: [(Int, String)]
valTagNames =
  [ (0, "int"), (1, "float"), (2, "string"), (3, "char"), (4, "nothing")
  , (5, "object"), (6, "list"), (7, "map")
  ]

waifuRuntimeASM :: String
waifuRuntimeASM = unlines
  [ ".text"
  , "list_new:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq $24, %rdi; call malloc; movq %rax, %r12"
  , "\tmovq $0, (%r12); movq $4, 8(%r12); movq $64, %rdi; call malloc; movq %rax, 16(%r12)"
  , "\tmovq %r12, %rax; leave; ret"
  , "list_grow:"
  , "\tpushq %rbp; movq %rsp, %rbp; movq %rdi, %r12"
  , "\tmovq 8(%r12), %rax; shlq $1, %rax; movq %rax, 8(%r12)"
  , "\tmovq %rax, %rcx; shlq $4, %rcx; movq 16(%r12), %rdi; movq %rcx, %rsi; call realloc"
  , "\tmovq %rax, 16(%r12); leave; ret"
  , "list_push:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tpushq %r12; pushq %r13; pushq %r14; pushq %r15"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; movq %rdx, %r14"
  , "\tmovq (%r12), %rax; cmpq 8(%r12), %rax; jl 1f; movq %r12, %rdi; call list_grow"
  , "1:\tmovq (%r12), %rax; movq 16(%r12), %r15; imulq $16, %rax, %rcx"
  , "\tmovq %r13, (%r15, %rcx); movq %r14, 8(%r15, %rcx)"
  , "\tincq (%r12); movq %r12, %rax"
  , "\tpopq %r15; popq %r14; popq %r13; popq %r12; leave; ret"
  , "list_prepend:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tpushq %r12; pushq %r13; pushq %r14; pushq %r15; pushq %rbx"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; movq %rdx, %r14"
  , "\tmovq (%r12), %rax; cmpq 8(%r12), %rax; jl .Lpp_nogrow"
  , "\tmovq %r12, %rdi; call list_grow"
  , ".Lpp_nogrow:\tmovq 16(%r12), %r15; movq (%r12), %rcx"
  , "\ttestq %rcx, %rcx; jz .Lpp_write"
  , "\tmovq %rcx, %rbx; decq %rbx"
  , ".Lpp_loop:\tmovq %rbx, %rax; imulq $16, %rax"
  , "\tmovq 8(%r15, %rax), %rdx; movq (%r15, %rax), %rsi"
  , "\tmovq %rbx, %rdi; incq %rdi; imulq $16, %rdi"
  , "\tmovq %rdx, 8(%r15, %rdi); movq %rsi, (%r15, %rdi)"
  , "\ttestq %rbx, %rbx; jz .Lpp_write; decq %rbx; jmp .Lpp_loop"
  , ".Lpp_write:\tmovq %r13, (%r15); movq %r14, 8(%r15); incq (%r12)"
  , "\tmovq %r12, %rax"
  , "\tpopq %rbx; popq %r15; popq %r14; popq %r13; popq %r12; leave; ret"
  , "val_eq:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r8; movq %rsi, %r9"
  , "\tmovq (%r8), %rax; cmpq (%r9), %rax; jne .Lveq_no"
  , "\tcmpq $2, %rax; je .Lveq_str"
  , "\tmovq 8(%r8), %rax; cmpq 8(%r9), %rax; sete %al; movzbq %al, %rax; jmp .Lveq_done"
  , ".Lveq_str:\tmovq 8(%r8), %rdi; movq 8(%r9), %rsi; call strcmp; testq %rax, %rax; sete %al; movzbq %al, %rax; jmp .Lveq_done"
  , ".Lveq_no:\txorq %rax, %rax"
  , ".Lveq_done:\tleave; ret"
  , "list_find_nth:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tpushq %r12; pushq %r13; pushq %r14; pushq %r15; pushq %rbx"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; movq %rdx, %r14; movq %rcx, %r15"
  , "\txorq %rbx, %rbx; xorq %rax, %rax"
  , ".Lfind_loop:\tcmpq (%r12), %rbx; jge .Lfind_fail"
  , "\tmovq 16(%r12), %r10; imulq $16, %rbx, %r11"
  , "\tleaq (%r10, %r11), %r8"
  , "\tmovq (%r8), %rcx; cmpq %r14, %rcx; jne .Lfind_next"
  , "\tcmpq $2, %r14; je .Lfind_str"
  , "\tmovq 8(%r8), %rcx; cmpq %r15, %rcx; jne .Lfind_next"
  , "\tjmp .Lfind_hit"
  , ".Lfind_str:\tmovq 8(%r8), %rdi; movq %r15, %rsi; call strcmp"
  , "\ttestq %rax, %rax; jnz .Lfind_next"
  , ".Lfind_hit:\tincq %rax; cmpq %r13, %rax; je .Lfind_ok"
  , ".Lfind_next:\tincq %rbx; jmp .Lfind_loop"
  , ".Lfind_ok:\tmovq %rbx, %rax"
  , "\tpopq %rbx; popq %r15; popq %r14; popq %r13; popq %r12; leave; ret"
  , ".Lfind_fail:\tmovq $-1, %rax"
  , "\tpopq %rbx; popq %r15; popq %r14; popq %r13; popq %r12; leave; ret"
  , "list_insert_after_nth:"
  , "\tpushq %rbp; movq %rsp, %rbp; subq $48, %rsp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; movq %rdx, %r14; movq %rcx, %r15"
  , "\tmovq %r8, -8(%rbp); movq %r9, -16(%rbp)"
  , "\tmovq %r12, %rdi; movq %r13, %rsi; movq %r14, %rdx; movq %r15, %rcx; call list_find_nth"
  , "\tcmpq $-1, %rax; je .Lins_fail"
  , "\tmovq %rax, %rbx; incq %rbx"
  , "\tmovq (%r12), %rax; cmpq 8(%r12), %rax; jl 4f; movq %r12, %rdi; call list_grow"
  , "4:\tmovq 16(%r12), %r15; movq (%r12), %rax; movq %rax, %rcx; subq %rbx, %rcx"
  , "\ttestq %rcx, %rcx; jz 5f"
  , "\timulq $16, %rbx, %r10; leaq 16(%r15, %r10), %rdi"
  , "\timulq $16, %rbx, %r11; leaq (%r15, %r11), %rsi"
  , "\timulq $16, %rcx, %rdx; call memmove"
  , "5:\timulq $16, %rbx, %rcx"
  , "\tmovq -8(%rbp), %rdx; movq %rdx, (%r15, %rcx)"
  , "\tmovq -16(%rbp), %rdx; movq %rdx, 8(%r15, %rcx); incq (%r12)"
  , "\tmovq $1, %rax; leave; ret"
  , ".Lins_fail:\tmovq $0, %rax; leave; ret"
  , "list_get_at:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %rbx"
  , "\tcmpq %rbx, (%r12); jle .Lget_fail"
  , "\tmovq 16(%r12), %r15; imulq $16, %rbx, %rcx"
  , "\tmovq 8(%r15, %rcx), %rax; leave; ret"
  , ".Lget_fail:\tmovq $-1, %rax; leave; ret"
  , "list_get_tag_at:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %rbx"
  , "\tcmpq %rbx, (%r12); jle .Lgt_fail"
  , "\tmovq 16(%r12), %r15; imulq $16, %rbx, %rcx"
  , "\tmovq (%r15, %rcx), %rax; leave; ret"
  , ".Lgt_fail:\tmovq $-1, %rax; leave; ret"
  , "list_len:"
  , "\tmovq (%rdi), %rax; ret"
  , "list_is_empty:"
  , "\tmovq (%rdi), %rax; testq %rax, %rax; sete %al; movzbq %al, %rax; ret"
  , "list_contains:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; movq %rdx, %r14"
  , "\tmovq %r12, %rdi; movq $1, %rsi; movq %r13, %rdx; movq %r14, %rcx; call list_find_nth"
  , "\tcmpq $-1, %rax; setne %al; movzbq %al, %rax; leave; ret"
  , "list_remove_nth_val:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; movq %rdx, %r14; movq %rcx, %r15"
  , "\tmovq %r12, %rdi; movq %r13, %rsi; movq %r14, %rdx; movq %r15, %rcx; call list_find_nth"
  , "\tcmpq $-1, %rax; je .Lrmvn_fail"
  , "\tmovq %r12, %rdi; movq %rax, %rsi; call list_remove_at_idx"
  , "\tleave; ret"
  , ".Lrmvn_fail:\tmovq $0, %rax; leave; ret"
  , "list_remove_at_idx:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %rbx"
  , "\tcmpq %rbx, (%r12); jle .Lrmv_fail"
  , "\tmovq 16(%r12), %r15; movq (%r12), %rax"
  , "\tmovq %rax, %rcx; subq %rbx, %rcx; decq %rcx"
  , "\ttestq %rcx, %rcx; jz 6f"
  , "\timulq $16, %rbx, %r10; leaq (%r15, %r10), %rdi"
  , "\timulq $16, %rbx, %r11; leaq 16(%r15, %r11), %rsi"
  , "\timulq $16, %rcx, %rdx; call memmove"
  , "6:\tdecq (%r12); movq $1, %rax; leave; ret"
  , ".Lrmv_fail:\tmovq $0, %rax; leave; ret"
  , "list_remove_after_val:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; movq %rdx, %r14; movq %rcx, %r15"
  , "\tmovq %r12, %rdi; movq %r13, %rsi; movq %r14, %rdx; movq %r15, %rcx; call list_find_nth"
  , "\tcmpq $-1, %rax; je .Lrmva_fail"
  , "\tmovq %rax, %rbx; incq %rbx; cmpq (%r12), %rbx; jge .Lrmva_fail"
  , "\tmovq %r12, %rdi; movq %rbx, %rsi; call list_remove_at_idx"
  , "\tleave; ret"
  , ".Lrmva_fail:\tmovq $0, %rax; leave; ret"
  -- list_to_string keeps buf (%r13) and cap (%r14); before appending an
  -- element it converts it to a string, then grows buf with realloc when
  -- strlen(buf) + strlen(piece) + 3 (", " + NUL) would exceed cap.
  , "list_to_string:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tpushq %r12; pushq %r13; pushq %r14; pushq %r15; pushq %rbx"
  , "\tsubq $24, %rsp"
  , "\tmovq %rdi, %r12"
  , "\tmovq $64, %rdi; call malloc; movq %rax, %r13"
  , "\tmovb $0, (%r13); movq $64, %r14; xorq %rbx, %rbx"
  , ".Llst_loop:\tcmpq (%r12), %rbx; jge .Llst_done"
  , "\tmovq 16(%r12), %r15; imulq $16, %rbx, %rcx"
  , "\tmovq (%r15, %rcx), %rax; movq 8(%r15, %rcx), %rdx"
  , "\tmovq %rdx, -56(%rbp)"
  , "\tcmpq $2, %rax; je .Llst_str"
  , "\tcmpq $6, %rax; je .Llst_sub"
  , "\tcmpq $3, %rax; je .Llst_chr"
  , "\tmovq %rdx, %rdi; call int_to_str; movq %rax, -48(%rbp); jmp .Llst_have"
  , ".Llst_str:\tmovq %rdx, -48(%rbp); jmp .Llst_have"
  , ".Llst_chr:\tmovq $2, %rdi; call malloc"
  , "\tmovq -56(%rbp), %rdx; movb %dl, (%rax); movb $0, 1(%rax)"
  , "\tmovq %rax, -48(%rbp); jmp .Llst_have"
  , ".Llst_sub:\tmovq %rdx, %rdi; call list_to_string; movq %rax, -48(%rbp)"
  , ".Llst_have:\tmovq %r13, %rdi; call strlen; movq %rax, -64(%rbp)"
  , "\tmovq -48(%rbp), %rdi; call strlen"
  , "\taddq -64(%rbp), %rax; addq $3, %rax"
  , "\tcmpq %r14, %rax; jle .Llst_fit"
  , "\tshlq $1, %rax; movq %rax, %r14"
  , "\tmovq %r13, %rdi; movq %r14, %rsi; call realloc; movq %rax, %r13"
  , ".Llst_fit:\ttestq %rbx, %rbx; jz .Llst_cat"
  , "\tmovq %r13, %rdi; leaq .LC_comma(%rip), %rsi; call strcat"
  , ".Llst_cat:\tmovq %r13, %rdi; movq -48(%rbp), %rsi; call strcat"
  , "\tincq %rbx; jmp .Llst_loop"
  , ".Llst_done:\tmovq %r13, %rax"
  , "\taddq $24, %rsp"
  , "\tpopq %rbx; popq %r15; popq %r14; popq %r13; popq %r12; leave; ret"
  -- val_to_string(tag, data) -> char*: stringify any tagged value.
  , "val_to_string:"
  , "\tpushq %rbp; movq %rsp, %rbp; subq $16, %rsp"
  , "\tmovq %rsi, -8(%rbp)"
  , "\tcmpq $2, %rdi; je .Lvts_str"
  , "\tcmpq $6, %rdi; je .Lvts_list"
  , "\tcmpq $3, %rdi; je .Lvts_chr"
  , "\tmovq %rsi, %rdi; call int_to_str; leave; ret"
  , ".Lvts_str:\tmovq -8(%rbp), %rax; leave; ret"
  , ".Lvts_list:\tmovq -8(%rbp), %rdi; call list_to_string; leave; ret"
  , ".Lvts_chr:\tmovq $2, %rdi; call malloc"
  , "\tmovq -8(%rbp), %rdx; movb %dl, (%rax); movb $0, 1(%rax); leave; ret"
  , "map_new:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq $24, %rdi; call malloc; movq %rax, %r12"
  , "\tmovq $0, (%r12); movq $4, 8(%r12); movq $128, %rdi; call malloc; movq %rax, 16(%r12)"
  , "\tmovq %r12, %rax; leave; ret"
  , "map_key_eq:"
  , "\tpushq %rbp; movq %rsp, %rbp; movq %rdi, %r8; movq %rsi, %r9"
  , "\tmovq (%r8), %rdi; movq %r9, %rsi; call strcmp; leave; ret"
  , "map_find_key:"
  , "\tpushq %rbp; movq %rsp, %rbp; xorq %rbx, %rbx"
  , ".Lmfind:\tcmpq (%rdi), %rbx; jge .Lmfind_fail"
  , "\tmovq 16(%rdi), %r10; imulq $24, %rbx, %r11"
  , "\tleaq (%r10, %r11), %r8; movq %rsi, %r9; pushq %rdi; pushq %rbx"
  , "\tmovq %r8, %rdi; movq %r9, %rsi; call map_key_eq"
  , "\tpopq %rbx; popq %rdi; testq %rax, %rax; jnz .Lmfind_ok"
  , "\tincq %rbx; jmp .Lmfind"
  , ".Lmfind_ok:\tmovq %rbx, %rax; leave; ret"
  , ".Lmfind_fail:\tmovq $-1, %rax; leave; ret"
  , "map_put:"
  , "\tpushq %rbp; movq %rsp, %rbp; subq $32, %rsp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; movq %rdx, %r14; movq %rcx, %r15"
  , "\tmovq %r14, -8(%rbp); movq %r15, -16(%rbp)"
  , "\tmovq %r12, %rdi; movq %r13, %rsi; call map_find_key"
  , "\tcmpq $-1, %rax; jne .Lmput_upd"
  , "\tmovq (%r12), %rax; cmpq 8(%r12), %rax; jl 7f"
  , "\tmovq (%r12), %rax; incq %rax; movq %rax, 8(%r12)"
  , "7:\tmovq 16(%r12), %r10; movq (%r12), %rbx; imulq $24, %rbx, %r11"
  , "\tmovq %r13, (%r10, %r11); movq -8(%rbp), %r14; movq %r14, 8(%r10, %r11)"
  , "\tmovq -16(%rbp), %r15; movq %r15, 16(%r10, %r11)"
  , "\tincq (%r12); jmp .Lmput_done"
  , ".Lmput_upd:\timulq $24, %rax, %r11; movq 16(%r12), %r10"
  , "\tmovq -8(%rbp), %r14; movq %r14, 8(%r10, %r11)"
  , "\tmovq -16(%rbp), %r15; movq %r15, 16(%r10, %r11)"
  , ".Lmput_done:\tmovq %r12, %rax; leave; ret"
  , "map_get:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; call map_find_key"
  , "\tcmpq $-1, %rax; je .Lmg_fail"
  , "\timulq $24, %rax, %rcx; movq 16(%r12), %r10"
  , "\tmovq 16(%r10, %rcx), %rax; leave; ret"
  , ".Lmg_fail:\tmovq $0, %rax; leave; ret"
  , "map_remove:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; call map_find_key"
  , "\tcmpq $-1, %rax; je .Lmr_fail"
  , "\tmovq %rax, %rbx; movq (%r12), %rax; decq %rax; cmpq %rbx, %rax; je .Lmr_last"
  , "\tmovq 16(%r12), %r10; imulq $24, %rbx, %r11"
  , "\tmovq %rax, %rcx; imulq $24, %rax, %r14"
  , "\tleaq (%r10, %r14), %rsi; leaq (%r10, %r11), %rdi; movq $24, %rcx; call memmove"
  , ".Lmr_last:\tdecq (%r12); movq $1, %rax; leave; ret"
  , ".Lmr_fail:\tmovq $0, %rax; leave; ret"
  , "map_contains:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; call map_find_key"
  , "\tcmpq $-1, %rax; setne %al; movzbq %al, %rax; leave; ret"
  , "str_len:"
  , "\tpushq %rbp; movq %rsp, %rbp; testq %rdi, %rdi; jz .Lslen0"
  , "\tcall strlen; leave; ret"
  , ".Lslen0:\txorq %rax, %rax; leave; ret"
  , "str_contains:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13; movq %r12, %rdi; movq %r13, %rsi; call strstr"
  , "\ttestq %rax, %rax; setne %al; movzbq %al, %rax; leave; ret"
  , "str_split:"
  , "\tpushq %rbp; movq %rsp, %rbp; subq $32, %rsp"
  , "\tmovq %rdi, -24(%rbp); movq %rsi, -8(%rbp)"
  , "\tmovq -24(%rbp), %rdi; call list_new; movq %rax, -16(%rbp)"
  , "\tmovq -24(%rbp), %rax; testq %rax, %rax; jz .Lsplit_done"
  , ".Lsplit_loop:"
  , "\tmovq -24(%rbp), %rdi; movq -8(%rbp), %rsi; call strstr"
  , "\ttestq %rax, %rax; jz .Lsplit_last"
  , "\tmovq %rax, %rbx; subq -24(%rbp), %rbx"
  , "\tpushq -24(%rbp); pushq %rbx"
  , "\tmovq (%rsp), %rdi; incq %rdi; call malloc; movq %rax, %r15"
  , "\tmovq %rax, %rdi; movq 8(%rsp), %rsi; movq (%rsp), %rdx; call strncpy"
  , "\tmovq %r15, %rdi; movq (%rsp), %rsi; movb $0, (%rdi, %rsi)"
  , "\tmovq -16(%rbp), %rdi; movq $2, %rsi; movq %r15, %rdx; call list_push"
  , "\tpopq %rbx; popq %rax"
  , "\tmovq %rbx, %rcx; addq %rax, %rcx"
  , "\tmovq -8(%rbp), %rdi; call strlen"
  , "\taddq %rax, %rcx; movq %rcx, -24(%rbp); jmp .Lsplit_loop"
  , ".Lsplit_last:"
  , "\tmovq -24(%rbp), %rdi; call strlen; testq %rax, %rax; jz .Lsplit_done"
  , "\tmovq %rax, %rbx; movq %rax, %rdi; incq %rdi; call malloc; movq %rax, %r15"
  , "\tmovq %r15, %rdi; movq -24(%rbp), %rsi; movq %rbx, %rdx; call strncpy"
  , "\tmovq %r15, %rdi; movq %rbx, %rsi; movb $0, (%rdi, %rsi)"
  , "\tmovq -16(%rbp), %rdi; movq $2, %rsi; movq %r15, %rdx; call list_push"
  , ".Lsplit_done:\tmovq -16(%rbp), %rax; leave; ret"
  , "darkness_print:"
  , "\tpushq %rbp; movq %rsp, %rbp"
  , "\tmovq %rdi, %r12; movq %rsi, %r13"
  , "\tleaq stderr(%rip), %rax; movq (%rax), %rdi"
  , "\tmovq %r12, %rsi; movq %r13, %rdx; xorq %rax, %rax; call fprintf"
  , "\tleave; ret"
  , ".section .rodata"
  , ".LC_comma: .string \", \""
  , ".LC_chr: .string \"%c\""
  ]
